language: c

before_script:
    - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
    - tar zxvf sourcemod-1.5.0-linux.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./compile.sh

after_script:
    - ls *.smx
